### ISSUE TITLE
CLoader in runPlatoDRS.py

### ISSUE THREAD

**Issue by WR1171** [uber-research/plato-research-dialogue-system#1]
Installed, wouldn't work - runPlatoRDS.py line 298 had

`cfg_parser = yaml.load(file, Loader=yaml.CLoader)`

Changed to

`cfg_parser = yaml.load(file, Loader=yaml.Loader)`

and it worked

**Comment by apapangelis** [comment]
Good catch, thanks!

**Comment by namanUIUC** [comment]
@WR1171 @apapangelis The issue is because pyyaml skips libyaml bindings (CLoader) if it's unable to find it. Check this out [[issue](https://github.com/yaml/pyyaml/issues/108#issuecomment-370459912)].

Alternative fix:

Install libyaml-dev (debian package)
`sudo apt-get install libyaml-dev`

Then upgrade pyyaml version
`pip install pyyaml --upgrade`

This should work without changing the code.
