### ISSUE TITLE
UnboundLocalError: local variable 'statistics' referenced before assignment

### ISSUE THREAD

**Issue by ccuiyuhan** [uber-research/plato-research-dialogue-system#11]
when I run plato gui --config CamRest_GUI_speech.yaml
I got an UnboundLocalError: local variable 'statistics' referenced before assignment
How to solve it? thank you!

**Comment by apapangelis** [comment]
Hi, I've made some minor fixes, I believe the UnBoundLocalError should be fixed. However there is another error still. This happens when you quit the GUI, correct?

**Comment by ccuiyuhan** [comment]
Yes，I met the same problem,how do you fix it？Could we have a discussion?，my email is ：937903992@qq.com   and  Wetchat ID: KAD4wei

**Comment by ccuiyuhan** [comment]
and can your GUI work？What's your GUI like ? when I press the button“start call”，there is nothing to happen，when i quit the GUI，i met “UnboundLocalError: local variable 'statistics' referenced before assignment
”

**Comment by apapangelis** [comment]
did you try to do "git pull" before trying again?

Also, does the regular "plato run --config CamRest_speech.yaml" work for you? If not it may have something to do with your audio / microphone.

**Comment by ccuiyuhan** [comment]
Thanks for replying ！I guess so，there is something with my mirophoe.So，if the microphone can work，when i run“plato run --config CamRest_dtl_simulator.yaml” , can I chat with the agent on the GUI？I mean when i say a sentence， can i receive a speech response from the agent？ Thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"apapangelis"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月14日(星期四) 凌晨2:13
收件人:&nbsp;"uber-research/plato-research-dialogue-system"<plato-research-dialogue-system@noreply.github.com&gt;;
抄送:&nbsp;"崔宇涵"<937903992@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [uber-research/plato-research-dialogue-system] UnboundLocalError: local variable 'statistics' referenced before assignment (#11)




did you try to do "git pull" before trying again?
 
Also, does the regular "plato run --config CamRest_speech.yaml" work for you? If not it may have something to do with your audio / microphone.

**Comment by ccuiyuhan** [comment]
i run “plato run --config CamRest_dtl_simulator.yaml” ，i met
 “WARNING: gTTS encountered an error. Falling back to sys TTS”
‘say’ is not an internal or external command, it's not a runnable program
sorry for bothering ，i’m a beginner

**Comment by ccuiyuhan** [comment]
Sorry for more questions，is there some specific introductions or papers that explain the method you applied in &nbsp;each module such as nlu、dst、dialogue policy、nlg and so on.Sincerely thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"apapangelis"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月14日(星期四) 凌晨2:13
收件人:&nbsp;"uber-research/plato-research-dialogue-system"<plato-research-dialogue-system@noreply.github.com&gt;;
抄送:&nbsp;"崔宇涵"<937903992@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [uber-research/plato-research-dialogue-system] UnboundLocalError: local variable 'statistics' referenced before assignment (#11)




did you try to do "git pull" before trying again?
 
Also, does the regular "plato run --config CamRest_speech.yaml" work for you? If not it may have something to do with your audio / microphone.

**Comment by apapangelis** [comment]
Hi, if gtts doesn't work for you and you are on Linux perhaps you can use 'espeak' instead of 'say':

https://linux.die.net/man/1/espeak

I can fix that in a future update.

As for specific methods, Plato is designed to support any statistical model, so it is up to you to train each component as you want. In the tutorials we provide some examples of neural nets with Ludwig. Also, there are a few reinforcement learning algorithms implemented (more to come) for dialogue policy learning. I hope this helps!

**Comment by ccuiyuhan** [comment]
Thanks for replying!
When I train the model，what is the data format like？How should I process the data to the correct form？
 And can i use the system to train chinese dataset ？

**Comment by apapangelis** [comment]
Hi, you have a few options but the easiest way is to:

- train your model outside of Plato (e.g. Ludwig, TensorFlow, Keras, any other framework)
- write a class that interfaces with your model (see for example [here](https://github.com/uber-research/plato-research-dialogue-system/blob/master/applications/cambridge_restaurants/camrest_nlu.py)) 

so, the data format is up to you - you only need to make sure that when plato calls your class the trained model is called correctly. 

In the NLU example above, you need to process an utterance (a string) and output a list of dialogue acts, so that class calls the model and processes its response into a list of dialogue acts. Similarly for other components or for joint / end-to-end architectures.

And yes, I don't see a problem with training your system using a Chinese dataset
